apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    name: database-config
    app: book-management
  namespace: mysql-api
data:
  NODE_ENV: mysql-api
  MYSQL_HOST: 10.136.6.9
  MYSQL_DATABASE: book-management-db
  MYSQL_USER: root
  PAGE_SIZE: '10'
